name: msani


channels:
  - conda-forge
  - rdkit

dependencies:
  - python>=3.10,<3.13
  - numpy
  - pandas
  - pip
  - rdkit>=2025.3.1
  - librdkit-dev
  - libboost-devel
  - scikit-build-core
  - openbabel
  - pyaml
  - gemmi
  - cmake<=3.29
  - pybind11
  - eigen
  - compilers
  - pkg-config
  - make
  - ninja
