[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "MolSanitizer"
version = "0.3.0"
description = "An Efficient In-silico Refinement pipeline for Virtual Screening (protonation, tautomers,...)"
readme = "README.md"
authors = [
    {name = "Thua-Phong Lam", email = "phong.lam@icm.uu.se"},
    {name = "Szymon Pach", email = "szymon.pach@icm.uu.se"},
    {name = "Israel Cabeza de Vaca", email = "israel.cabezadevaca@icm.uu.se"}
]
license = {text = "GPL 2.0"}
classifiers = [
    "Development Status :: 3 - Alpha",
    "License :: OSI Approved :: GPL 2.0",
    "Programming Language :: Python :: 3.11",
    "Operating System :: POSIX :: Linux",
    "Topic :: Scientific/Engineering :: Chemistry",
    "Topic :: Scientific/Engineering :: Drug Discovery",
]
keywords = ["docking", "drug design"]
requires-python = ">=3.9,<3.12"
dependencies = [
    "markdown",
    "pandas",
    "numpy",
    "rdkit>=2024.09.3",
    "meeko",
    "scipy",
    "pyaml"
]

[project.urls]
Homepage = "https://github.com/phonglam3103/MolSanitizer.git"

[project.scripts]
msani = "msani.cli:main"
msani_batch = "msani.batchmode:main"
strain = "msani.filtering.strain_filter:main"
charger = "msani.moltransform.ionizer:main"
tautomerizer = "msani.moltransform.tautomerizer:main"
gen3d = "msani.conformers.conformers:main"

[tool.setuptools]
packages = ["msani"]


