# Configuration file for MolSanitizer batch mode
# LINE_PER_JOB: Number of compounds per job
# TIME_LIMIT: Time limit for each job in hours (default: 96 hour)
# MAX_JOBS: Maximum number of jobs running at the same time
# TIMEOUT: Timeout for the initial embedding of each compound in minutes (default: 2 minutes)

SLURM_ACCOUNT: 'naiss2023-3-39'
LINES_PER_JOB: 200
TIME_LIMIT: 96
MAX_JOBS: 500
TIMEOUT: 2

