name: Generate Changelog

on:
  push:
    branches:
      - main

jobs:
  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Changelog
        uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Commit and Push Changes
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          CHANGELOG_MD="CHANGELOG.md"
          CHANGELOG_RST="docs/source/changes.rst"
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

          # Check if there are any changes in CHANGELOG.md
          if git diff --quiet "$CHANGELOG_MD"; then
            echo "No changes detected in $CHANGELOG_MD. Skipping commit."
          else
            echo "Changes detected in $CHANGELOG_MD. Installing pandoc..."
            sudo apt-get update
            sudo apt-get install -y pandoc

            git add "$CHANGELOG_MD"
            pandoc "$CHANGELOG_MD" -o "$CHANGELOG_RST"
            git add "$CHANGELOG_RST"
            git commit -m "Update changelog for tag ${{ github.ref_name }}"

            # Push the changes to the default branch
            git remote set-url origin https://x-access-token:${PERSONAL_ACCESS_TOKEN}@github.com/${{ github.repository }}.git
            git push origin HEAD:main
          fi
