name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
      
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            python-version: "3.10"
          - os: ubuntu-latest
            python-version: "3.11"
          - os: ubuntu-22.04
            python-version: "3.10"
          - os: ubuntu-22.04
            python-version: "3.11"
          - os: macos-latest
            python-version: "3.11"
          - os: windows-latest
            python-version: "3.11"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: 'latest'
          environment-file: environment.yml
          environment-name: msani
          create-args: python=${{ matrix.python-version }}
          condarc: |
            channels:
              - conda-forge
              - rdkit
          cache-downloads: true
          cache-environment: true

      # Linux/macOS install
      - name: Install in editable mode (Unix)
        if: runner.os != 'Windows'
        shell: bash -l {0}
        run: pip install -e .

      # Windows install
      - name: Install in editable mode (Windows)
        if: runner.os == 'Windows'
        shell: powershell
        run: micromamba run -n msani pip install -e .


      # Linux/macOS tests
      - name: Run unittests (Unix)
        if: runner.os != 'Windows'
        shell: bash -l {0}
        run: |
          python -m unittest test/test_msani.py
          python -m unittest test/test_validation_sets.py

      # Windows tests
      - name: Run unittests (Windows)
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          micromamba run -n msani python -m unittest test/test_msani.py
          micromamba run -n msani python -m unittest test/test_validation_sets.py
