name: Update Version on Tag Push

on:
  push:
    tags:
      - "*"  # Trigger on any tag

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Ensure all history is fetched

    - name: Switch to default branch
      run: |
        DEFAULT_BRANCH=$(git remote show origin | awk '/HEAD branch/ {print $NF}')
        git checkout $DEFAULT_BRANCH

    - name: Extract tag and update version
      run: |
        VERSION=$(git describe --tags --abbrev=0)
        echo "Updating version to $VERSION"

        # Update version in pyproject.toml
        sed -i "s/^version = \".*\"/version = \"$VERSION\"/" pyproject.toml

        # Update __version__ in Python files
        sed -i "s/^__version__ = \".*\"/__version__ = \"$VERSION\"/" MolSanitizer/molSanitizer.py
        sed -i "s/^__version__ = \".*\"/__version__ = \"$VERSION\"/" MolSanitizer/msani_batch.py

    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add pyproject.toml MolSanitizer/molSanitizer.py MolSanitizer/msani_batch.py
        git commit -m "Update version to $VERSION"
        git push origin HEAD:$DEFAULT_BRANCH
